"""sec migration

Revision ID: 0c64f25446cb
Revises: c293e1530309
Create Date: 2020-04-01 12:44:55.361431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c64f25446cb'
down_revision = 'c293e1530309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column('comments', sa.Column('disabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
